version: '3.8'
services:
  openadserve:
    build: .
    ports:
      - "8787:8787"
    environment:
      - POSTGRES_DSN=${POSTGRES_DSN}
      - REDIS_ADDR=${REDIS_ADDR}
      - CLICKHOUSE_DSN=${CLICKHOUSE_DSN}
      - SERVICE_NAME=openadserve-demo
      - RATE_LIMIT_ENABLED=true
      - RATE_LIMIT_CAPACITY=100
      - TOKEN_SECRET=${TOKEN_SECRET}
      - DEBUG_TRACE=1
      - CTR_OPTIMIZATION_ENABLED=false
      - RELOAD_INTERVAL=5m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8787/health"]
      interval: 30s
      timeout: 10s
      retries: 3