auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9096
common:
  path_prefix: /tmp
  storage:
    filesystem:
      chunks_directory: /tmp/chunks
      rules_directory: /tmp/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
limits_config:
  # Disable structured metadata as this configuration uses an older
  # storage schema (v11) and boltdb-shipper indexing which are
  # incompatible with the defaults of newer Loki versions. Without this
  # flag Loki refuses to start, expecting schema v13 and the tsdb index
  # type. See error message in logs for details.
  allow_structured_metadata: false
  # Increase ingestion rate limits for development
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  max_streams_per_user: 10000
  max_line_size: 256000
