name: openadserve-demo
region: nyc
services:
  - name: openadserve
    dockerfile_path: Dockerfile
    source_dir: /
    github:
      repo: patrickwarner/openadserve
      branch: main
      deploy_on_push: true
    http_port: 8787
    instance_count: 1
    instance_size_slug: basic-xs  # $4/month
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 30
    envs:
      - key: SERVICE_NAME
        value: openadserve-demo
      - key: PORT
        value: "8787"
      - key: RATE_LIMIT_ENABLED
        value: "true"
      - key: RATE_LIMIT_CAPACITY
        value: "100"
      - key: DEBUG_TRACE
        value: "1"
      - key: CTR_OPTIMIZATION_ENABLED
        value: "false"
      - key: RELOAD_INTERVAL
        value: "5m"
      - key: POSTGRES_DSN
        type: SECRET
        value: "YOUR_POSTGRES_URL"
      - key: REDIS_ADDR
        type: SECRET
        value: "YOUR_REDIS_URL"
      - key: TOKEN_SECRET
        type: SECRET
        value: "GENERATE_RANDOM_SECRET"
databases:
  - name: openadserve-db
    engine: PG
    version: "15"
    size: db-s-dev-database  # $7/month
    num_nodes: 1